package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpCustPriceGroup generated by hbm2java
 */
@Entity
@Table(name = "tmp_cust_price_group")
public class TmpCustPriceGroup implements java.io.Serializable {

	private long custPriceGroupId;
	private String custCode;
	private Long productTypeId;
	private String productBuyerGroupId;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpCustPriceGroup() {
	}

	public TmpCustPriceGroup(long custPriceGroupId, String custCode) {
		this.custPriceGroupId = custPriceGroupId;
		this.custCode = custCode;
	}

	public TmpCustPriceGroup(long custPriceGroupId, String custCode, Long productTypeId, String productBuyerGroupId,
			String dtsSystem, Date dtsUpdate) {
		this.custPriceGroupId = custPriceGroupId;
		this.custCode = custCode;
		this.productTypeId = productTypeId;
		this.productBuyerGroupId = productBuyerGroupId;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "cust_price_group_id", unique = true, nullable = false)
	public long getCustPriceGroupId() {
		return this.custPriceGroupId;
	}

	public void setCustPriceGroupId(long custPriceGroupId) {
		this.custPriceGroupId = custPriceGroupId;
	}

	@Column(name = "cust_code", nullable = false, length = 32)
	public String getCustCode() {
		return this.custCode;
	}

	public void setCustCode(String custCode) {
		this.custCode = custCode;
	}

	@Column(name = "product_type_id")
	public Long getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(Long productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Column(name = "product_buyer_group_id", length = 16)
	public String getProductBuyerGroupId() {
		return this.productBuyerGroupId;
	}

	public void setProductBuyerGroupId(String productBuyerGroupId) {
		this.productBuyerGroupId = productBuyerGroupId;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
