package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpInvoice generated by hbm2java
 */
@Entity
@Table(name = "tmp_invoice")
public class TmpInvoice implements java.io.Serializable {

	private Long runningNo;
	private Long orderProductId;
	private String invoiceNo;
	private String soNo;
	private String itemCode;
	private Long amount;
	private String productBuyerGroupId;
	private BigDecimal price;
	private String productCurrency;
	private String productUnitId;
	private Date invoiceDate;
	private Date invoiceEtd;
	private Date invoiceEta;
	private Long importStatus;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpInvoice() {
	}

	public TmpInvoice(Long orderProductId, String invoiceNo, String soNo, String itemCode, Long amount,
			String productBuyerGroupId, BigDecimal price, String productCurrency, String productUnitId,
			Date invoiceDate, Date invoiceEtd, Date invoiceEta, Long importStatus, String dtsSystem, Date dtsUpdate) {
		this.orderProductId = orderProductId;
		this.invoiceNo = invoiceNo;
		this.soNo = soNo;
		this.itemCode = itemCode;
		this.amount = amount;
		this.productBuyerGroupId = productBuyerGroupId;
		this.price = price;
		this.productCurrency = productCurrency;
		this.productUnitId = productUnitId;
		this.invoiceDate = invoiceDate;
		this.invoiceEtd = invoiceEtd;
		this.invoiceEta = invoiceEta;
		this.importStatus = importStatus;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "running_no", unique = true, nullable = false)
	public Long getRunningNo() {
		return this.runningNo;
	}

	public void setRunningNo(Long runningNo) {
		this.runningNo = runningNo;
	}

	@Column(name = "order_product_id")
	public Long getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(Long orderProductId) {
		this.orderProductId = orderProductId;
	}

	@Column(name = "invoice_no", length = 32)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "so_no", length = 32)
	public String getSoNo() {
		return this.soNo;
	}

	public void setSoNo(String soNo) {
		this.soNo = soNo;
	}

	@Column(name = "item_code", length = 32)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "amount")
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "product_buyer_group_id", length = 32)
	public String getProductBuyerGroupId() {
		return this.productBuyerGroupId;
	}

	public void setProductBuyerGroupId(String productBuyerGroupId) {
		this.productBuyerGroupId = productBuyerGroupId;
	}

	@Column(name = "price", precision = 20, scale = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "product_currency", length = 16)
	public String getProductCurrency() {
		return this.productCurrency;
	}

	public void setProductCurrency(String productCurrency) {
		this.productCurrency = productCurrency;
	}

	@Column(name = "product_unit_id", length = 16)
	public String getProductUnitId() {
		return this.productUnitId;
	}

	public void setProductUnitId(String productUnitId) {
		this.productUnitId = productUnitId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invoice_date", length = 19)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invoice_etd", length = 19)
	public Date getInvoiceEtd() {
		return this.invoiceEtd;
	}

	public void setInvoiceEtd(Date invoiceEtd) {
		this.invoiceEtd = invoiceEtd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invoice_eta", length = 19)
	public Date getInvoiceEta() {
		return this.invoiceEta;
	}

	public void setInvoiceEta(Date invoiceEta) {
		this.invoiceEta = invoiceEta;
	}

	@Column(name = "import_status")
	public Long getImportStatus() {
		return this.importStatus;
	}

	public void setImportStatus(Long importStatus) {
		this.importStatus = importStatus;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
