package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpOrdDetail generated by hbm2java
 */
@Entity
@Table(name = "tmp_ord_detail")
public class TmpOrdDetail implements java.io.Serializable {

	private long orderProductId;
	private Long orderId;
	private Long productId;
	private Long amount;
	private Long status;
	private BigDecimal price;
	private String productUnitId;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpOrdDetail() {
	}

	public TmpOrdDetail(long orderProductId) {
		this.orderProductId = orderProductId;
	}

	public TmpOrdDetail(long orderProductId, Long orderId, Long productId, Long amount, Long status, BigDecimal price,
			String productUnitId, String dtsSystem, Date dtsUpdate) {
		this.orderProductId = orderProductId;
		this.orderId = orderId;
		this.productId = productId;
		this.amount = amount;
		this.status = status;
		this.price = price;
		this.productUnitId = productUnitId;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "order_product_id", unique = true, nullable = false)
	public long getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(long orderProductId) {
		this.orderProductId = orderProductId;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "product_id")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "amount")
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "status")
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Column(name = "price", precision = 20, scale = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "product_unit_id", length = 16)
	public String getProductUnitId() {
		return this.productUnitId;
	}

	public void setProductUnitId(String productUnitId) {
		this.productUnitId = productUnitId;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
