package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpOrderStatus generated by hbm2java
 */
@Entity
@Table(name = "tmp_order_status")
public class TmpOrderStatus implements java.io.Serializable {

	private String orderStatusId;
	private String orderStatusName;
	private String orderStatusDescription;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpOrderStatus() {
	}

	public TmpOrderStatus(String orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	public TmpOrderStatus(String orderStatusId, String orderStatusName, String orderStatusDescription, String dtsSystem,
			Date dtsUpdate) {
		this.orderStatusId = orderStatusId;
		this.orderStatusName = orderStatusName;
		this.orderStatusDescription = orderStatusDescription;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "order_status_id", unique = true, nullable = false, length = 2)
	public String getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(String orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "order_status_name", length = 100)
	public String getOrderStatusName() {
		return this.orderStatusName;
	}

	public void setOrderStatusName(String orderStatusName) {
		this.orderStatusName = orderStatusName;
	}

	@Column(name = "order_status_description")
	public String getOrderStatusDescription() {
		return this.orderStatusDescription;
	}

	public void setOrderStatusDescription(String orderStatusDescription) {
		this.orderStatusDescription = orderStatusDescription;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
