package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmpOrdAddressId generated by hbm2java
 */
@Embeddable
public class TmpOrdAddressId implements java.io.Serializable {

	private long orderAddressId;
	private long orderId;

	public TmpOrdAddressId() {
	}

	public TmpOrdAddressId(long orderAddressId, long orderId) {
		this.orderAddressId = orderAddressId;
		this.orderId = orderId;
	}

	@Column(name = "order_address_id", nullable = false)
	public long getOrderAddressId() {
		return this.orderAddressId;
	}

	public void setOrderAddressId(long orderAddressId) {
		this.orderAddressId = orderAddressId;
	}

	@Column(name = "order_id", nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpOrdAddressId))
			return false;
		TmpOrdAddressId castOther = (TmpOrdAddressId) other;

		return (this.getOrderAddressId() == castOther.getOrderAddressId())
				&& (this.getOrderId() == castOther.getOrderId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getOrderAddressId();
		result = 37 * result + (int) this.getOrderId();
		return result;
	}

}
