package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpOrdAddress generated by hbm2java
 */
@Entity
@Table(name = "tmp_ord_address")
public class TmpOrdAddress implements java.io.Serializable {

	private TmpOrdAddressId id;
	private String orderFname;
	private String orderLname;
	private String orderAddr;
	private String subdistrict;
	private String district;
	private Long orderCountryId;
	private String orderProvince;
	private String orderZipcode;
	private String orderTel;
	private String orderMobile;
	private String fax;
	private String email;
	private String description;
	private Long type;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpOrdAddress() {
	}

	public TmpOrdAddress(TmpOrdAddressId id) {
		this.id = id;
	}

	public TmpOrdAddress(TmpOrdAddressId id, String orderFname, String orderLname, String orderAddr, String subdistrict,
			String district, Long orderCountryId, String orderProvince, String orderZipcode, String orderTel,
			String orderMobile, String fax, String email, String description, Long type, String dtsSystem,
			Date dtsUpdate) {
		this.id = id;
		this.orderFname = orderFname;
		this.orderLname = orderLname;
		this.orderAddr = orderAddr;
		this.subdistrict = subdistrict;
		this.district = district;
		this.orderCountryId = orderCountryId;
		this.orderProvince = orderProvince;
		this.orderZipcode = orderZipcode;
		this.orderTel = orderTel;
		this.orderMobile = orderMobile;
		this.fax = fax;
		this.email = email;
		this.description = description;
		this.type = type;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderAddressId", column = @Column(name = "order_address_id", nullable = false) ),
			@AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false) ) })
	public TmpOrdAddressId getId() {
		return this.id;
	}

	public void setId(TmpOrdAddressId id) {
		this.id = id;
	}

	@Column(name = "order_fname", length = 100)
	public String getOrderFname() {
		return this.orderFname;
	}

	public void setOrderFname(String orderFname) {
		this.orderFname = orderFname;
	}

	@Column(name = "order_lname", length = 100)
	public String getOrderLname() {
		return this.orderLname;
	}

	public void setOrderLname(String orderLname) {
		this.orderLname = orderLname;
	}

	@Column(name = "order_addr", length = 100)
	public String getOrderAddr() {
		return this.orderAddr;
	}

	public void setOrderAddr(String orderAddr) {
		this.orderAddr = orderAddr;
	}

	@Column(name = "subdistrict", length = 50)
	public String getSubdistrict() {
		return this.subdistrict;
	}

	public void setSubdistrict(String subdistrict) {
		this.subdistrict = subdistrict;
	}

	@Column(name = "district", length = 50)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "order_country_id")
	public Long getOrderCountryId() {
		return this.orderCountryId;
	}

	public void setOrderCountryId(Long orderCountryId) {
		this.orderCountryId = orderCountryId;
	}

	@Column(name = "order_province", length = 100)
	public String getOrderProvince() {
		return this.orderProvince;
	}

	public void setOrderProvince(String orderProvince) {
		this.orderProvince = orderProvince;
	}

	@Column(name = "order_zipcode", length = 32)
	public String getOrderZipcode() {
		return this.orderZipcode;
	}

	public void setOrderZipcode(String orderZipcode) {
		this.orderZipcode = orderZipcode;
	}

	@Column(name = "order_tel", length = 100)
	public String getOrderTel() {
		return this.orderTel;
	}

	public void setOrderTel(String orderTel) {
		this.orderTel = orderTel;
	}

	@Column(name = "order_mobile", length = 100)
	public String getOrderMobile() {
		return this.orderMobile;
	}

	public void setOrderMobile(String orderMobile) {
		this.orderMobile = orderMobile;
	}

	@Column(name = "fax", length = 32)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 64)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type")
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
