package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpPaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "tmp_payment_method")
public class TmpPaymentMethod implements java.io.Serializable {

	private String paymentMethodId;
	private String paymentMethodName;
	private String description;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpPaymentMethod() {
	}

	public TmpPaymentMethod(String paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	public TmpPaymentMethod(String paymentMethodId, String paymentMethodName, String description, String dtsSystem,
			Date dtsUpdate) {
		this.paymentMethodId = paymentMethodId;
		this.paymentMethodName = paymentMethodName;
		this.description = description;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "payment_method_id", unique = true, nullable = false, length = 16)
	public String getPaymentMethodId() {
		return this.paymentMethodId;
	}

	public void setPaymentMethodId(String paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	@Column(name = "payment_method_name", length = 100)
	public String getPaymentMethodName() {
		return this.paymentMethodName;
	}

	public void setPaymentMethodName(String paymentMethodName) {
		this.paymentMethodName = paymentMethodName;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
