package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProductBrandGroup generated by hbm2java
 */
@Entity
@Table(name = "tmp_product_brand_group")
public class TmpProductBrandGroup implements java.io.Serializable {

	private TmpProductBrandGroupId id;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpProductBrandGroup() {
	}

	public TmpProductBrandGroup(TmpProductBrandGroupId id) {
		this.id = id;
	}

	public TmpProductBrandGroup(TmpProductBrandGroupId id, String dtsSystem, Date dtsUpdate) {
		this.id = id;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productTypeId", column = @Column(name = "product_type_id", nullable = false) ),
			@AttributeOverride(name = "brandGroupId", column = @Column(name = "brand_group_id", nullable = false) ) })
	public TmpProductBrandGroupId getId() {
		return this.id;
	}

	public void setId(TmpProductBrandGroupId id) {
		this.id = id;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
