package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProductType generated by hbm2java
 */
@Entity
@Table(name = "tmp_product_type")
public class TmpProductType implements java.io.Serializable {

	private long productTypeId;
	private String productTypeName;
	private Long productTypeParentId;
	private String productTypeDescription;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpProductType() {
	}

	public TmpProductType(long productTypeId) {
		this.productTypeId = productTypeId;
	}

	public TmpProductType(long productTypeId, String productTypeName, Long productTypeParentId,
			String productTypeDescription, String dtsSystem, Date dtsUpdate) {
		this.productTypeId = productTypeId;
		this.productTypeName = productTypeName;
		this.productTypeParentId = productTypeParentId;
		this.productTypeDescription = productTypeDescription;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "product_type_id", unique = true, nullable = false)
	public long getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(long productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Column(name = "product_type_name", length = 100)
	public String getProductTypeName() {
		return this.productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	@Column(name = "product_type_parent_id")
	public Long getProductTypeParentId() {
		return this.productTypeParentId;
	}

	public void setProductTypeParentId(Long productTypeParentId) {
		this.productTypeParentId = productTypeParentId;
	}

	@Column(name = "product_type_description", length = 1024)
	public String getProductTypeDescription() {
		return this.productTypeDescription;
	}

	public void setProductTypeDescription(String productTypeDescription) {
		this.productTypeDescription = productTypeDescription;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
