package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProductPrice generated by hbm2java
 */
@Entity
@Table(name = "tmp_product_price")
public class TmpProductPrice implements java.io.Serializable {

	private TmpProductPriceId id;
	private BigDecimal amount;
	private String productUnitId;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpProductPrice() {
	}

	public TmpProductPrice(TmpProductPriceId id) {
		this.id = id;
	}

	public TmpProductPrice(TmpProductPriceId id, BigDecimal amount, String productUnitId, String dtsSystem,
			Date dtsUpdate) {
		this.id = id;
		this.amount = amount;
		this.productUnitId = productUnitId;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productCode", column = @Column(name = "product_code", nullable = false, length = 32) ),
			@AttributeOverride(name = "productBuyerGroupId", column = @Column(name = "product_buyer_group_id", nullable = false, length = 32) ),
			@AttributeOverride(name = "productCurrency", column = @Column(name = "product_currency", nullable = false, length = 3) ) })
	public TmpProductPriceId getId() {
		return this.id;
	}

	public void setId(TmpProductPriceId id) {
		this.id = id;
	}

	@Column(name = "amount", precision = 20, scale = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "product_unit_id", length = 16)
	public String getProductUnitId() {
		return this.productUnitId;
	}

	public void setProductUnitId(String productUnitId) {
		this.productUnitId = productUnitId;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
