package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmpProductPriceId generated by hbm2java
 */
@Embeddable
public class TmpProductPriceId implements java.io.Serializable {

	private String productCode;
	private String productBuyerGroupId;
	private String productCurrency;

	public TmpProductPriceId() {
	}

	public TmpProductPriceId(String productCode, String productBuyerGroupId, String productCurrency) {
		this.productCode = productCode;
		this.productBuyerGroupId = productBuyerGroupId;
		this.productCurrency = productCurrency;
	}

	@Column(name = "product_code", nullable = false, length = 32)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "product_buyer_group_id", nullable = false, length = 32)
	public String getProductBuyerGroupId() {
		return this.productBuyerGroupId;
	}

	public void setProductBuyerGroupId(String productBuyerGroupId) {
		this.productBuyerGroupId = productBuyerGroupId;
	}

	@Column(name = "product_currency", nullable = false, length = 3)
	public String getProductCurrency() {
		return this.productCurrency;
	}

	public void setProductCurrency(String productCurrency) {
		this.productCurrency = productCurrency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpProductPriceId))
			return false;
		TmpProductPriceId castOther = (TmpProductPriceId) other;

		return ((this.getProductCode() == castOther.getProductCode()) || (this.getProductCode() != null
				&& castOther.getProductCode() != null && this.getProductCode().equals(castOther.getProductCode())))
				&& ((this.getProductBuyerGroupId() == castOther.getProductBuyerGroupId())
						|| (this.getProductBuyerGroupId() != null && castOther.getProductBuyerGroupId() != null
								&& this.getProductBuyerGroupId().equals(castOther.getProductBuyerGroupId())))
				&& ((this.getProductCurrency() == castOther.getProductCurrency())
						|| (this.getProductCurrency() != null && castOther.getProductCurrency() != null
								&& this.getProductCurrency().equals(castOther.getProductCurrency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductCode() == null ? 0 : this.getProductCode().hashCode());
		result = 37 * result + (getProductBuyerGroupId() == null ? 0 : this.getProductBuyerGroupId().hashCode());
		result = 37 * result + (getProductCurrency() == null ? 0 : this.getProductCurrency().hashCode());
		return result;
	}

}
