package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProductModel generated by hbm2java
 */
@Entity
@Table(name = "tmp_product_model")
public class TmpProductModel implements java.io.Serializable {

	private String productModelId;
	private String productModelName;
	private String description;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpProductModel() {
	}

	public TmpProductModel(String productModelId) {
		this.productModelId = productModelId;
	}

	public TmpProductModel(String productModelId, String productModelName, String description, String dtsSystem,
			Date dtsUpdate) {
		this.productModelId = productModelId;
		this.productModelName = productModelName;
		this.description = description;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "product_model_id", unique = true, nullable = false, length = 16)
	public String getProductModelId() {
		return this.productModelId;
	}

	public void setProductModelId(String productModelId) {
		this.productModelId = productModelId;
	}

	@Column(name = "product_model_name", length = 100)
	public String getProductModelName() {
		return this.productModelName;
	}

	public void setProductModelName(String productModelName) {
		this.productModelName = productModelName;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
