package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProductYear generated by hbm2java
 */
@Entity
@Table(name = "tmp_product_year")
public class TmpProductYear implements java.io.Serializable {

	private String productYearId;
	private String productYearName;
	private String description;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpProductYear() {
	}

	public TmpProductYear(String productYearId) {
		this.productYearId = productYearId;
	}

	public TmpProductYear(String productYearId, String productYearName, String description, String dtsSystem,
			Date dtsUpdate) {
		this.productYearId = productYearId;
		this.productYearName = productYearName;
		this.description = description;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "product_year_id", unique = true, nullable = false, length = 16)
	public String getProductYearId() {
		return this.productYearId;
	}

	public void setProductYearId(String productYearId) {
		this.productYearId = productYearId;
	}

	@Column(name = "product_year_name", length = 100)
	public String getProductYearName() {
		return this.productYearName;
	}

	public void setProductYearName(String productYearName) {
		this.productYearName = productYearName;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
