package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProductUnit generated by hbm2java
 */
@Entity
@Table(name = "tmp_product_unit")
public class TmpProductUnit implements java.io.Serializable {

	private String productUnitId;
	private String productUnitName;
	private String description;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpProductUnit() {
	}

	public TmpProductUnit(String productUnitId) {
		this.productUnitId = productUnitId;
	}

	public TmpProductUnit(String productUnitId, String productUnitName, String description, String dtsSystem,
			Date dtsUpdate) {
		this.productUnitId = productUnitId;
		this.productUnitName = productUnitName;
		this.description = description;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "product_unit_id", unique = true, nullable = false, length = 16)
	public String getProductUnitId() {
		return this.productUnitId;
	}

	public void setProductUnitId(String productUnitId) {
		this.productUnitId = productUnitId;
	}

	@Column(name = "product_unit_name", length = 100)
	public String getProductUnitName() {
		return this.productUnitName;
	}

	public void setProductUnitName(String productUnitName) {
		this.productUnitName = productUnitName;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
