package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProductItemGroup generated by hbm2java
 */
@Entity
@Table(name = "tmp_product_item_group")
public class TmpProductItemGroup implements java.io.Serializable {

	private String productItemGroupId;
	private String productItemGroupName;
	private String description;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpProductItemGroup() {
	}

	public TmpProductItemGroup(String productItemGroupId) {
		this.productItemGroupId = productItemGroupId;
	}

	public TmpProductItemGroup(String productItemGroupId, String productItemGroupName, String description,
			String dtsSystem, Date dtsUpdate) {
		this.productItemGroupId = productItemGroupId;
		this.productItemGroupName = productItemGroupName;
		this.description = description;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "product_item_group_id", unique = true, nullable = false, length = 16)
	public String getProductItemGroupId() {
		return this.productItemGroupId;
	}

	public void setProductItemGroupId(String productItemGroupId) {
		this.productItemGroupId = productItemGroupId;
	}

	@Column(name = "product_item_group_name", length = 100)
	public String getProductItemGroupName() {
		return this.productItemGroupName;
	}

	public void setProductItemGroupName(String productItemGroupName) {
		this.productItemGroupName = productItemGroupName;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
