package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmpProductBrandGroupId generated by hbm2java
 */
@Embeddable
public class TmpProductBrandGroupId implements java.io.Serializable {

	private long productTypeId;
	private long brandGroupId;

	public TmpProductBrandGroupId() {
	}

	public TmpProductBrandGroupId(long productTypeId, long brandGroupId) {
		this.productTypeId = productTypeId;
		this.brandGroupId = brandGroupId;
	}

	@Column(name = "product_type_id", nullable = false)
	public long getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(long productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Column(name = "brand_group_id", nullable = false)
	public long getBrandGroupId() {
		return this.brandGroupId;
	}

	public void setBrandGroupId(long brandGroupId) {
		this.brandGroupId = brandGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpProductBrandGroupId))
			return false;
		TmpProductBrandGroupId castOther = (TmpProductBrandGroupId) other;

		return (this.getProductTypeId() == castOther.getProductTypeId())
				&& (this.getBrandGroupId() == castOther.getBrandGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProductTypeId();
		result = 37 * result + (int) this.getBrandGroupId();
		return result;
	}

}
