package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpRo generated by hbm2java
 */
@Entity
@Table(name = "tmp_ro")
public class TmpRo implements java.io.Serializable {

	private long orderProductId;
	private Long orderId;
	private String roNumber;
	private Long productId;
	private String itemId;
	private String productName;
	private String category;
	private String custAccount;
	private String custName;
	private String numberSeqCode;
	private String site;
	private String warehouse;
	private Date reqShipDate;
	private Date reqReceiptDate;
	private Long amount;
	private Long status;
	private BigDecimal salesPrice;
	private String unit;
	private String productBuyerGroupId;
	private String currencyCode;
	private String termCode;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;
	private Long runningNumber;
	private Date importDateTime;
	private String salesId;
	private Long importStatus;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpRo() {
	}

	public TmpRo(long orderProductId) {
		this.orderProductId = orderProductId;
	}

	public TmpRo(long orderProductId, Long orderId, String roNumber, Long productId, String itemId, String productName,
			String category, String custAccount, String custName, String numberSeqCode, String site, String warehouse,
			Date reqShipDate, Date reqReceiptDate, Long amount, Long status, BigDecimal salesPrice, String unit,
			String productBuyerGroupId, String currencyCode, String termCode, String userCreate, String userUpdate,
			Date timeCreate, Date timeUpdate, Long runningNumber, Date importDateTime, String salesId,
			Long importStatus, String dtsSystem, Date dtsUpdate) {
		this.orderProductId = orderProductId;
		this.orderId = orderId;
		this.roNumber = roNumber;
		this.productId = productId;
		this.itemId = itemId;
		this.productName = productName;
		this.category = category;
		this.custAccount = custAccount;
		this.custName = custName;
		this.numberSeqCode = numberSeqCode;
		this.site = site;
		this.warehouse = warehouse;
		this.reqShipDate = reqShipDate;
		this.reqReceiptDate = reqReceiptDate;
		this.amount = amount;
		this.status = status;
		this.salesPrice = salesPrice;
		this.unit = unit;
		this.productBuyerGroupId = productBuyerGroupId;
		this.currencyCode = currencyCode;
		this.termCode = termCode;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
		this.runningNumber = runningNumber;
		this.importDateTime = importDateTime;
		this.salesId = salesId;
		this.importStatus = importStatus;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id

	@Column(name = "order_product_id", unique = true, nullable = false)
	public long getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(long orderProductId) {
		this.orderProductId = orderProductId;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "ro_number", length = 100)
	public String getRoNumber() {
		return this.roNumber;
	}

	public void setRoNumber(String roNumber) {
		this.roNumber = roNumber;
	}

	@Column(name = "product_id")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "item_id", length = 32)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "category")
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "cust_account", length = 32)
	public String getCustAccount() {
		return this.custAccount;
	}

	public void setCustAccount(String custAccount) {
		this.custAccount = custAccount;
	}

	@Column(name = "cust_name")
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "number_seq_code")
	public String getNumberSeqCode() {
		return this.numberSeqCode;
	}

	public void setNumberSeqCode(String numberSeqCode) {
		this.numberSeqCode = numberSeqCode;
	}

	@Column(name = "site")
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "warehouse")
	public String getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "req_ship_date", length = 19)
	public Date getReqShipDate() {
		return this.reqShipDate;
	}

	public void setReqShipDate(Date reqShipDate) {
		this.reqShipDate = reqShipDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "req_receipt_date", length = 19)
	public Date getReqReceiptDate() {
		return this.reqReceiptDate;
	}

	public void setReqReceiptDate(Date reqReceiptDate) {
		this.reqReceiptDate = reqReceiptDate;
	}

	@Column(name = "amount")
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "status")
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Column(name = "sales_price", precision = 20, scale = 10)
	public BigDecimal getSalesPrice() {
		return this.salesPrice;
	}

	public void setSalesPrice(BigDecimal salesPrice) {
		this.salesPrice = salesPrice;
	}

	@Column(name = "unit", length = 16)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "product_buyer_group_id", length = 32)
	public String getProductBuyerGroupId() {
		return this.productBuyerGroupId;
	}

	public void setProductBuyerGroupId(String productBuyerGroupId) {
		this.productBuyerGroupId = productBuyerGroupId;
	}

	@Column(name = "currency_code", length = 16)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "term_code", length = 16)
	public String getTermCode() {
		return this.termCode;
	}

	public void setTermCode(String termCode) {
		this.termCode = termCode;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

	@Column(name = "running_number")
	public Long getRunningNumber() {
		return this.runningNumber;
	}

	public void setRunningNumber(Long runningNumber) {
		this.runningNumber = runningNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "import_date_time", length = 19)
	public Date getImportDateTime() {
		return this.importDateTime;
	}

	public void setImportDateTime(Date importDateTime) {
		this.importDateTime = importDateTime;
	}

	@Column(name = "sales_id", length = 32)
	public String getSalesId() {
		return this.salesId;
	}

	public void setSalesId(String salesId) {
		this.salesId = salesId;
	}

	@Column(name = "import_status")
	public Long getImportStatus() {
		return this.importStatus;
	}

	public void setImportStatus(Long importStatus) {
		this.importStatus = importStatus;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
