package com.starboard.b2b.model.sync;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpSo generated by hbm2java
 */
@Entity
@Table(name = "tmp_so")
public class TmpSo implements java.io.Serializable {

	private Long runningNo;
	private Long orderProductId;
	private String soNo;
	private String itemCode;
	private String roCode;
	private Long amount;
	private String productBuyerGroupId;
	private BigDecimal price;
	private String productCurrency;
	private String productUnitId;
	private String shippingId;
	private String termCode;
	private String paymentMethodId;
	private Date expectShipmentDate;
	private Long importStatus;
	private String dtsSystem;
	private Date dtsUpdate;

	public TmpSo() {
	}

	public TmpSo(Long orderProductId, String soNo, String itemCode, String roCode, Long amount,
			String productBuyerGroupId, BigDecimal price, String productCurrency, String productUnitId,
			String shippingId, String termCode, String paymentMethodId, Date expectShipmentDate, Long importStatus,
			String dtsSystem, Date dtsUpdate) {
		this.orderProductId = orderProductId;
		this.soNo = soNo;
		this.itemCode = itemCode;
		this.roCode = roCode;
		this.amount = amount;
		this.productBuyerGroupId = productBuyerGroupId;
		this.price = price;
		this.productCurrency = productCurrency;
		this.productUnitId = productUnitId;
		this.shippingId = shippingId;
		this.termCode = termCode;
		this.paymentMethodId = paymentMethodId;
		this.expectShipmentDate = expectShipmentDate;
		this.importStatus = importStatus;
		this.dtsSystem = dtsSystem;
		this.dtsUpdate = dtsUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "running_no", unique = true, nullable = false)
	public Long getRunningNo() {
		return this.runningNo;
	}

	public void setRunningNo(Long runningNo) {
		this.runningNo = runningNo;
	}

	@Column(name = "order_product_id")
	public Long getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(Long orderProductId) {
		this.orderProductId = orderProductId;
	}

	@Column(name = "so_no", length = 32)
	public String getSoNo() {
		return this.soNo;
	}

	public void setSoNo(String soNo) {
		this.soNo = soNo;
	}

	@Column(name = "item_code", length = 32)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "ro_code", length = 100)
	public String getRoCode() {
		return this.roCode;
	}

	public void setRoCode(String roCode) {
		this.roCode = roCode;
	}

	@Column(name = "amount")
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "product_buyer_group_id", length = 32)
	public String getProductBuyerGroupId() {
		return this.productBuyerGroupId;
	}

	public void setProductBuyerGroupId(String productBuyerGroupId) {
		this.productBuyerGroupId = productBuyerGroupId;
	}

	@Column(name = "price", precision = 20, scale = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "product_currency", length = 16)
	public String getProductCurrency() {
		return this.productCurrency;
	}

	public void setProductCurrency(String productCurrency) {
		this.productCurrency = productCurrency;
	}

	@Column(name = "product_unit_id", length = 16)
	public String getProductUnitId() {
		return this.productUnitId;
	}

	public void setProductUnitId(String productUnitId) {
		this.productUnitId = productUnitId;
	}

	@Column(name = "shipping_id", length = 16)
	public String getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(String shippingId) {
		this.shippingId = shippingId;
	}

	@Column(name = "term_code", length = 16)
	public String getTermCode() {
		return this.termCode;
	}

	public void setTermCode(String termCode) {
		this.termCode = termCode;
	}

	@Column(name = "payment_method_id", length = 16)
	public String getPaymentMethodId() {
		return this.paymentMethodId;
	}

	public void setPaymentMethodId(String paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expect_shipment_date", length = 19)
	public Date getExpectShipmentDate() {
		return this.expectShipmentDate;
	}

	public void setExpectShipmentDate(Date expectShipmentDate) {
		this.expectShipmentDate = expectShipmentDate;
	}

	@Column(name = "import_status")
	public Long getImportStatus() {
		return this.importStatus;
	}

	public void setImportStatus(Long importStatus) {
		this.importStatus = importStatus;
	}

	@Column(name = "dts_system", length = 32)
	public String getDtsSystem() {
		return this.dtsSystem;
	}

	public void setDtsSystem(String dtsSystem) {
		this.dtsSystem = dtsSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dts_update", length = 19)
	public Date getDtsUpdate() {
		return this.dtsUpdate;
	}

	public void setDtsUpdate(Date dtsUpdate) {
		this.dtsUpdate = dtsUpdate;
	}

}
