/*
-- Query: SELECT  m.model_id as id, m.model_name as name FROM stb.model m
LIMIT 0, 1000

-- Date: 2015-09-16 10:46
*/
INSERT INTO `model` (`id`,`name`) VALUES ('KD','KODE');
INSERT INTO `model` (`id`,`name`) VALUES ('RO','RIO');
INSERT INTO `model` (`id`,`name`) VALUES ('ST','START');
INSERT INTO `model` (`id`,`name`) VALUES ('FM','FORMULA');
INSERT INTO `model` (`id`,`name`) VALUES ('AT','ATOM');
INSERT INTO `model` (`id`,`name`) VALUES ('CA','CARVE');
INSERT INTO `model` (`id`,`name`) VALUES ('FU','FUTURA');
INSERT INTO `model` (`id`,`name`) VALUES ('FL','FLARE');
INSERT INTO `model` (`id`,`name`) VALUES ('PKF','PROKIDS FLARE');
INSERT INTO `model` (`id`,`name`) VALUES ('PKG','PROKIDS GO');
INSERT INTO `model` (`id`,`name`) VALUES ('PKM','PROKIDS FORMULA');
INSERT INTO `model` (`id`,`name`) VALUES ('PKQ','PROKIDS QUAD');
INSERT INTO `model` (`id`,`name`) VALUES ('GM','GEMINI');
INSERT INTO `model` (`id`,`name`) VALUES ('PH','PHANTOM');
INSERT INTO `model` (`id`,`name`) VALUES ('SR','SERENITY');
INSERT INTO `model` (`id`,`name`) VALUES ('SU','SUPER');
INSERT INTO `model` (`id`,`name`) VALUES ('GO','GO');
INSERT INTO `model` (`id`,`name`) VALUES ('IS','ISONIC');
INSERT INTO `model` (`id`,`name`) VALUES ('INF11','INFLATABLE 11\'');
INSERT INTO `model` (`id`,`name`) VALUES ('EV','EVO');
INSERT INTO `model` (`id`,`name`) VALUES ('QC','QUAD CONVERTABLE');
INSERT INTO `model` (`id`,`name`) VALUES ('QD','QUAD');
INSERT INTO `model` (`id`,`name`) VALUES ('UPTK','TIKI');
INSERT INTO `model` (`id`,`name`) VALUES ('UPTF','SUP TUFSKIN');
INSERT INTO `model` (`id`,`name`) VALUES ('UPIM','IMPOSSIBLE');
INSERT INTO `model` (`id`,`name`) VALUES ('UPPD','POD');
INSERT INTO `model` (`id`,`name`) VALUES ('UPRU','RUSH');
INSERT INTO `model` (`id`,`name`) VALUES ('UPSE','SEVEN ELEVEN');
INSERT INTO `model` (`id`,`name`) VALUES ('UPP85','PRO 8\'5\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPPK','POCKET ROCKET');
INSERT INTO `model` (`id`,`name`) VALUES ('UPW810','WIDE POINT 8\'10\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPCV','CONVERSE');
INSERT INTO `model` (`id`,`name`) VALUES ('UPHE','HERO');
INSERT INTO `model` (`id`,`name`) VALUES ('UPP91','PRO 9\'1\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPP98','PRO 9\'8\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPWH','WHOPPER');
INSERT INTO `model` (`id`,`name`) VALUES ('UPWE','WHOPPER EXTRA');
INSERT INTO `model` (`id`,`name`) VALUES ('UPGU','GUN');
INSERT INTO `model` (`id`,`name`) VALUES ('UPP10','PRO 10\'3\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPDR','DRIVE');
INSERT INTO `model` (`id`,`name`) VALUES ('UPNG','NRG FITNESS');
INSERT INTO `model` (`id`,`name`) VALUES ('UPW10','WIDE POINT 10\'5\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPBL','BLEND');
INSERT INTO `model` (`id`,`name`) VALUES ('UPAV','AVANTI');
INSERT INTO `model` (`id`,`name`) VALUES ('UPBD','BIG DADDY');
INSERT INTO `model` (`id`,`name`) VALUES ('UPFS','FISHERMAN');
INSERT INTO `model` (`id`,`name`) VALUES ('UPOC','OCEAN RESCUE');
INSERT INTO `model` (`id`,`name`) VALUES ('UPBE','BIG EASY');
INSERT INTO `model` (`id`,`name`) VALUES ('UPAL','ATLAS');
INSERT INTO `model` (`id`,`name`) VALUES ('UPAC','ACE');
INSERT INTO `model` (`id`,`name`) VALUES ('UPRA','RACE');
INSERT INTO `model` (`id`,`name`) VALUES ('UPCO','COAST RUNNER');
INSERT INTO `model` (`id`,`name`) VALUES ('UPOO','OPEN OCEAN');
INSERT INTO `model` (`id`,`name`) VALUES ('UPK15','K-15');
INSERT INTO `model` (`id`,`name`) VALUES ('UPK14','K-14');
INSERT INTO `model` (`id`,`name`) VALUES ('UPNR','NOSE RIDER');
INSERT INTO `model` (`id`,`name`) VALUES ('UPAE','ATLAS EXTRA');
INSERT INTO `model` (`id`,`name`) VALUES ('UPSQ','SQUIRT');
INSERT INTO `model` (`id`,`name`) VALUES ('UPRB','RACE BOP');
INSERT INTO `model` (`id`,`name`) VALUES ('UPSR','SURF RACE');
INSERT INTO `model` (`id`,`name`) VALUES ('UPTO','TOURING');
INSERT INTO `model` (`id`,`name`) VALUES ('UPP77','PRO 7\'7\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPP80','PRO 8\'0\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPW82','WIDE POINT 8\'2\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPW95','WIDE POINT 9\'5\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPIN09','INFLATABLE 9\'0\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPIN10','INFLATABLE 10\'0\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPIN11','INFLATABLE 11\'0\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPAP','ACE PRO');
INSERT INTO `model` (`id`,`name`) VALUES ('UPGP','GUN PRO');
INSERT INTO `model` (`id`,`name`) VALUES ('UPNE','THE NEW');
INSERT INTO `model` (`id`,`name`) VALUES ('UPW78','WIDE POINT 7\'8\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPP74','PRO 7\'4\"');
INSERT INTO `model` (`id`,`name`) VALUES ('UPIN12','INFLATABLE 12\'6\"');
INSERT INTO `model` (`id`,`name`) VALUES ('PA','PURE ACID');
INSERT INTO `model` (`id`,`name`) VALUES ('ET','EVIL TWIN');
INSERT INTO `model` (`id`,`name`) VALUES ('UPEL','ELEMENT');
INSERT INTO `model` (`id`,`name`) VALUES ('IN10','INFLATABLE 10\'');
INSERT INTO `model` (`id`,`name`) VALUES ('IN12','INFLATABLE 12\'');
INSERT INTO `model` (`id`,`name`) VALUES ('UPFW','FLAT WATER');
INSERT INTO `model` (`id`,`name`) VALUES ('UPAS','ALL STAR');
