package com.starboard.b2b.model;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BrandGroup generated by hbm2java
 */
@Entity
@Table(name = "brand_group")
public class BrandGroup implements java.io.Serializable {

	private long brandGroupId;
	private String brandGroupName;
	private String brandGroupDescription;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public BrandGroup() {
	}

	public BrandGroup(long brandGroupId) {
		this.brandGroupId = brandGroupId;
	}

	public BrandGroup(long brandGroupId, String brandGroupName, String brandGroupDescription, String userCreate,
			String userUpdate, Date timeCreate, Date timeUpdate) {
		this.brandGroupId = brandGroupId;
		this.brandGroupName = brandGroupName;
		this.brandGroupDescription = brandGroupDescription;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "brand_group_id", unique = true, nullable = false)
	public long getBrandGroupId() {
		return this.brandGroupId;
	}

	public void setBrandGroupId(long brandGroupId) {
		this.brandGroupId = brandGroupId;
	}

	@Column(name = "brand_group_name", length = 100)
	public String getBrandGroupName() {
		return this.brandGroupName;
	}

	public void setBrandGroupName(String brandGroupName) {
		this.brandGroupName = brandGroupName;
	}

	@Column(name = "brand_group_description", length = 1024)
	public String getBrandGroupDescription() {
		return this.brandGroupDescription;
	}

	public void setBrandGroupDescription(String brandGroupDescription) {
		this.brandGroupDescription = brandGroupDescription;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
