package com.starboard.b2b.model;
// Generated Sep 26, 2015 11:05:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustBrandGroup generated by hbm2java
 */
@Entity
@Table(name = "cust_brand_group")
public class CustBrandGroup implements java.io.Serializable {

	private CustBrandGroupId id;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public CustBrandGroup() {
	}

	public CustBrandGroup(CustBrandGroupId id) {
		this.id = id;
	}

	public CustBrandGroup(CustBrandGroupId id, String userCreate, String userUpdate, Date timeCreate, Date timeUpdate) {
		this.id = id;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "custId", column = @Column(name = "cust_id", nullable = false) ),
			@AttributeOverride(name = "brandGroupId", column = @Column(name = "brand_group_id", nullable = false) ) })
	public CustBrandGroupId getId() {
		return this.id;
	}

	public void setId(CustBrandGroupId id) {
		this.id = id;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
