package com.starboard.b2b.model;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document", catalog = "stb")
public class Document implements java.io.Serializable {

	private long documentId;
	private String documentFilenameOriginal;
	private String documentFilenameRuning;
	private String documentPath;
	private String documentContenttype;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public Document() {
	}

	public Document(long documentId, String documentFilenameOriginal, String documentFilenameRuning,
			String documentPath, String documentContenttype) {
		this.documentId = documentId;
		this.documentFilenameOriginal = documentFilenameOriginal;
		this.documentFilenameRuning = documentFilenameRuning;
		this.documentPath = documentPath;
		this.documentContenttype = documentContenttype;
	}

	public Document(long documentId, String documentFilenameOriginal, String documentFilenameRuning,
			String documentPath, String documentContenttype, String userCreate, String userUpdate, Date timeCreate,
			Date timeUpdate) {
		this.documentId = documentId;
		this.documentFilenameOriginal = documentFilenameOriginal;
		this.documentFilenameRuning = documentFilenameRuning;
		this.documentPath = documentPath;
		this.documentContenttype = documentContenttype;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "document_id", unique = true, nullable = false)
	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	@Column(name = "document_filename_original", nullable = false)
	public String getDocumentFilenameOriginal() {
		return this.documentFilenameOriginal;
	}

	public void setDocumentFilenameOriginal(String documentFilenameOriginal) {
		this.documentFilenameOriginal = documentFilenameOriginal;
	}

	@Column(name = "document_filename_runing", nullable = false)
	public String getDocumentFilenameRuning() {
		return this.documentFilenameRuning;
	}

	public void setDocumentFilenameRuning(String documentFilenameRuning) {
		this.documentFilenameRuning = documentFilenameRuning;
	}

	@Column(name = "document_path", nullable = false)
	public String getDocumentPath() {
		return this.documentPath;
	}

	public void setDocumentPath(String documentPath) {
		this.documentPath = documentPath;
	}

	@Column(name = "document_contenttype", nullable = false, length = 100)
	public String getDocumentContenttype() {
		return this.documentContenttype;
	}

	public void setDocumentContenttype(String documentContenttype) {
		this.documentContenttype = documentContenttype;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
