package com.starboard.b2b.model;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdRunning generated by hbm2java
 */
@Entity
@Table(name = "id_running", catalog = "stb")
public class IdRunning implements java.io.Serializable {

	private String id;
	private String pkId;
	private String name;
	private long runningNo;
	private Date timeCreate;
	private Date timeUpdate;

	public IdRunning() {
	}

	public IdRunning(String id, long runningNo) {
		this.id = id;
		this.runningNo = runningNo;
	}

	public IdRunning(String id, String pkId, String name, long runningNo, Date timeCreate, Date timeUpdate) {
		this.id = id;
		this.pkId = pkId;
		this.name = name;
		this.runningNo = runningNo;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "pk_id", length = 32)
	public String getPkId() {
		return this.pkId;
	}

	public void setPkId(String pkId) {
		this.pkId = pkId;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "running_no", nullable = false)
	public long getRunningNo() {
		return this.runningNo;
	}

	public void setRunningNo(long runningNo) {
		this.runningNo = runningNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
