package com.starboard.b2b.model;
// Generated Oct 12, 2015 10:55:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductItemGroup generated by hbm2java
 */
@Entity
@Table(name = "product_item_group")
public class ProductItemGroup implements java.io.Serializable {

	private String productItemGroupId;
	private String productItemGroupName;
	private String description;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public ProductItemGroup() {
	}

	public ProductItemGroup(String productItemGroupId) {
		this.productItemGroupId = productItemGroupId;
	}

	public ProductItemGroup(String productItemGroupId, String productItemGroupName, String description,
			String userCreate, String userUpdate, Date timeCreate, Date timeUpdate) {
		this.productItemGroupId = productItemGroupId;
		this.productItemGroupName = productItemGroupName;
		this.description = description;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "product_item_group_id", unique = true, nullable = false, length = 16)
	public String getProductItemGroupId() {
		return this.productItemGroupId;
	}

	public void setProductItemGroupId(String productItemGroupId) {
		this.productItemGroupId = productItemGroupId;
	}

	@Column(name = "product_item_group_name", length = 100)
	public String getProductItemGroupName() {
		return this.productItemGroupName;
	}

	public void setProductItemGroupName(String productItemGroupName) {
		this.productItemGroupName = productItemGroupName;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
