package com.starboard.b2b.model;
// Generated Oct 12, 2015 10:55:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductCalendar generated by hbm2java
 */
@Entity
@Table(name = "product_calendar")
public class ProductCalendar implements java.io.Serializable {

	private Integer idCalendar;
	private String descriptions;
	private Date dateEvent;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public ProductCalendar() {
	}

	public ProductCalendar(String descriptions, Date dateEvent, String userCreate, String userUpdate, Date timeCreate,
			Date timeUpdate) {
		this.descriptions = descriptions;
		this.dateEvent = dateEvent;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_calendar", unique = true, nullable = false)
	public Integer getIdCalendar() {
		return this.idCalendar;
	}

	public void setIdCalendar(Integer idCalendar) {
		this.idCalendar = idCalendar;
	}

	@Column(name = "descriptions", nullable = false)
	public String getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_event", nullable = false, length = 19)
	public Date getDateEvent() {
		return this.dateEvent;
	}

	public void setDateEvent(Date dateEvent) {
		this.dateEvent = dateEvent;
	}

	@Column(name = "user_create", nullable = false, length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", nullable = false, length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", nullable = false, length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", nullable = false, length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
