package com.starboard.b2b.model;
// Generated Sep 26, 2015 11:05:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductCat generated by hbm2java
 */
@Entity
@Table(name = "product_cat")
public class ProductCat implements java.io.Serializable {

	private long productCatId;
	private String productCatName;
	private Long productCatParentId;
	private String productCatDescription;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public ProductCat() {
	}

	public ProductCat(long productCatId) {
		this.productCatId = productCatId;
	}

	public ProductCat(long productCatId, String productCatName, Long productCatParentId, String productCatDescription,
			String userCreate, String userUpdate, Date timeCreate, Date timeUpdate) {
		this.productCatId = productCatId;
		this.productCatName = productCatName;
		this.productCatParentId = productCatParentId;
		this.productCatDescription = productCatDescription;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "product_cat_id", unique = true, nullable = false)
	public long getProductCatId() {
		return this.productCatId;
	}

	public void setProductCatId(long productCatId) {
		this.productCatId = productCatId;
	}

	@Column(name = "product_cat_name", length = 100)
	public String getProductCatName() {
		return this.productCatName;
	}

	public void setProductCatName(String productCatName) {
		this.productCatName = productCatName;
	}

	@Column(name = "product_cat_parent_id")
	public Long getProductCatParentId() {
		return this.productCatParentId;
	}

	public void setProductCatParentId(Long productCatParentId) {
		this.productCatParentId = productCatParentId;
	}

	@Column(name = "product_cat_description", length = 1024)
	public String getProductCatDescription() {
		return this.productCatDescription;
	}

	public void setProductCatDescription(String productCatDescription) {
		this.productCatDescription = productCatDescription;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
