package com.starboard.b2b.model;
// Generated Sep 26, 2015 11:05:02 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductCatList generated by hbm2java
 */
@Entity
@Table(name = "product_cat_list")
public class ProductCatList implements java.io.Serializable {

	private ProductCatListId id;

	public ProductCatList() {
	}

	public ProductCatList(ProductCatListId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false) ),
			@AttributeOverride(name = "productCatId", column = @Column(name = "product_cat_id", nullable = false) ) })
	public ProductCatListId getId() {
		return this.id;
	}

	public void setId(ProductCatListId id) {
		this.id = id;
	}

}
