package com.starboard.b2b.model;
// Generated Sep 26, 2015 11:05:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductBuyerGroup generated by hbm2java
 */
@Entity
@Table(name = "product_buyer_group")
public class ProductBuyerGroup implements java.io.Serializable {

	private String productBuyerGroupId;
	private String productBuyerGroupName;
	private String description;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public ProductBuyerGroup() {
	}

	public ProductBuyerGroup(String productBuyerGroupId) {
		this.productBuyerGroupId = productBuyerGroupId;
	}

	public ProductBuyerGroup(String productBuyerGroupId, String productBuyerGroupName, String description,
			String userCreate, String userUpdate, Date timeCreate, Date timeUpdate) {
		this.productBuyerGroupId = productBuyerGroupId;
		this.productBuyerGroupName = productBuyerGroupName;
		this.description = description;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "product_buyer_group_id", unique = true, nullable = false, length = 32)
	public String getProductBuyerGroupId() {
		return this.productBuyerGroupId;
	}

	public void setProductBuyerGroupId(String productBuyerGroupId) {
		this.productBuyerGroupId = productBuyerGroupId;
	}

	@Column(name = "product_buyer_group_name", length = 100)
	public String getProductBuyerGroupName() {
		return this.productBuyerGroupName;
	}

	public void setProductBuyerGroupName(String productBuyerGroupName) {
		this.productBuyerGroupName = productBuyerGroupName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
