package com.starboard.b2b.model;
// Generated Sep 26, 2015 11:05:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductPriceId generated by hbm2java
 */
@Embeddable
public class ProductPriceId implements java.io.Serializable {

	private String productCode;
	private String productPriceGroupId;
	private String productCurrency;

	public ProductPriceId() {
	}

	public ProductPriceId(String productCode, String productPriceGroupId, String productCurrency) {
		this.productCode = productCode;
		this.productPriceGroupId = productPriceGroupId;
		this.productCurrency = productCurrency;
	}

	@Column(name = "product_code", nullable = false, length = 32)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "product_price_group_id", nullable = false, length = 32)
	public String getProductPriceGroupId() {
		return this.productPriceGroupId;
	}

	public void setProductPriceGroupId(String productPriceGroupId) {
		this.productPriceGroupId = productPriceGroupId;
	}

	@Column(name = "product_currency", nullable = false, length = 3)
	public String getProductCurrency() {
		return this.productCurrency;
	}

	public void setProductCurrency(String productCurrency) {
		this.productCurrency = productCurrency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductPriceId))
			return false;
		ProductPriceId castOther = (ProductPriceId) other;

		return ((this.getProductCode() == castOther.getProductCode()) || (this.getProductCode() != null
				&& castOther.getProductCode() != null && this.getProductCode().equals(castOther.getProductCode())))
				&& ((this.getProductPriceGroupId() == castOther.getProductPriceGroupId())
						|| (this.getProductPriceGroupId() != null && castOther.getProductPriceGroupId() != null
								&& this.getProductPriceGroupId().equals(castOther.getProductPriceGroupId())))
				&& ((this.getProductCurrency() == castOther.getProductCurrency())
						|| (this.getProductCurrency() != null && castOther.getProductCurrency() != null
								&& this.getProductCurrency().equals(castOther.getProductCurrency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductCode() == null ? 0 : this.getProductCode().hashCode());
		result = 37 * result + (getProductPriceGroupId() == null ? 0 : this.getProductPriceGroupId().hashCode());
		result = 37 * result + (getProductCurrency() == null ? 0 : this.getProductCurrency().hashCode());
		return result;
	}

}
