package com.starboard.b2b.model;
// Generated Oct 12, 2015 10:55:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductImg generated by hbm2java
 */
@Entity
@Table(name = "product_img")
public class ProductImg implements java.io.Serializable {

	private Long productImgId;
	private String productCode;
	private String imgPath;
	private String productImgType;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public ProductImg() {
	}

	public ProductImg(String productCode, String imgPath, String productImgType, String userCreate, String userUpdate) {
		this.productCode = productCode;
		this.imgPath = imgPath;
		this.productImgType = productImgType;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
	}

	public ProductImg(String productCode, String imgPath, String productImgType, String userCreate, String userUpdate,
			Date timeCreate, Date timeUpdate) {
		this.productCode = productCode;
		this.imgPath = imgPath;
		this.productImgType = productImgType;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_img_id", unique = true, nullable = false)
	public Long getProductImgId() {
		return this.productImgId;
	}

	public void setProductImgId(Long productImgId) {
		this.productImgId = productImgId;
	}

	@Column(name = "product_code", nullable = false, length = 32)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "img_path", nullable = false)
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Column(name = "product_img_type", nullable = false, length = 1)
	public String getProductImgType() {
		return this.productImgType;
	}

	public void setProductImgType(String productImgType) {
		this.productImgType = productImgType;
	}

	@Column(name = "user_create", nullable = false, length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", nullable = false, length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
