package com.starboard.b2b.model;
// Generated Oct 12, 2015 10:55:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductCatListId generated by hbm2java
 */
@Embeddable
public class ProductCatListId implements java.io.Serializable {

	private long productId;
	private long productCatId;

	public ProductCatListId() {
	}

	public ProductCatListId(long productId, long productCatId) {
		this.productId = productId;
		this.productCatId = productCatId;
	}

	@Column(name = "product_id", nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "product_cat_id", nullable = false)
	public long getProductCatId() {
		return this.productCatId;
	}

	public void setProductCatId(long productCatId) {
		this.productCatId = productCatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductCatListId))
			return false;
		ProductCatListId castOther = (ProductCatListId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getProductCatId() == castOther.getProductCatId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProductId();
		result = 37 * result + (int) this.getProductCatId();
		return result;
	}

}
