package com.starboard.b2b.model;
// Generated Oct 25, 2015 1:54:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductSoCategory generated by hbm2java
 */
@Entity
@Table(name = "product_so_category")
public class ProductSoCategory implements java.io.Serializable {

	private String soCategory;
	private String site;
	private String warehouse;
	private String saleOrderCat;
	private String email;
	private String userCreate;
	private String userUpdate;
	private Date timeCreate;
	private Date timeUpdate;

	public ProductSoCategory() {
	}

	public ProductSoCategory(String soCategory, String site, String warehouse, String saleOrderCat) {
		this.soCategory = soCategory;
		this.site = site;
		this.warehouse = warehouse;
		this.saleOrderCat = saleOrderCat;
	}

	public ProductSoCategory(String soCategory, String site, String warehouse, String saleOrderCat, String email,
			String userCreate, String userUpdate, Date timeCreate, Date timeUpdate) {
		this.soCategory = soCategory;
		this.site = site;
		this.warehouse = warehouse;
		this.saleOrderCat = saleOrderCat;
		this.email = email;
		this.userCreate = userCreate;
		this.userUpdate = userUpdate;
		this.timeCreate = timeCreate;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "so_category", unique = true, nullable = false, length = 32)
	public String getSoCategory() {
		return this.soCategory;
	}

	public void setSoCategory(String soCategory) {
		this.soCategory = soCategory;
	}

	@Column(name = "site", nullable = false, length = 32)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "warehouse", nullable = false, length = 32)
	public String getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "sale_order_cat", nullable = false, length = 32)
	public String getSaleOrderCat() {
		return this.saleOrderCat;
	}

	public void setSaleOrderCat(String saleOrderCat) {
		this.saleOrderCat = saleOrderCat;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "user_create", length = 32)
	public String getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	@Column(name = "user_update", length = 32)
	public String getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(String userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_create", length = 19)
	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
